import Head from 'next/head'
import { formatDuration, intervalToDuration, addMinutes, Duration } from 'date-fns'
import { useState, useEffect } from 'react';

export default function Home() {

  const [end] = useState<Date>(addMinutes(new Date(), 50))
  const [formattedDuration, setFormattedDuration] = useState<string>("")

  useEffect(() => { 
    const interval = setInterval(() => {
     updateDuration()
    }, 1000);
    return () => clearInterval(interval);
  }, [])
  
  const updateDuration = () => {
    const duration = intervalToDuration({
      start: new Date(), 
      end
    })

    setFormattedDuration(formatDuration(duration, { format: ['hours', 'minutes', 'seconds'] }))
  }

  return (
    <div className='px-8 py-8'>
      <Head>
        <title>Ambient Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍅</text></svg>"
        />
      </Head>

      <main>
        <h1>Ambient Pomodoro 🍅</h1>
        <p>{formattedDuration}</p>
      </main>
    </div>
  );
}
