import Head from 'next/head'

export default function Home() {
  return (
    <div className='px-8 py-8'>
      <Head>
        <title>Ambient Pomodoro</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🍅</text></svg>"
        />
      </Head>

      <main>
        <h1>Ambient Pomodoro 🍅</h1>
      </main>
    </div>
  );
}
